[window]
dimensions = { columns = 100, lines = 24 }
dynamic_padding = true
decorations = "Full"
padding = { x = 8, y = 8 }
dynamic_title = true
opacity = 0.9

[font]
normal = { family = "Hasklug Nerd Font Mono" }
size = 12

[colors.cursor]
text = '#242424'
cursor = '#E95420'

[colors.primary]
background = '#242424'
foreground = '#ffffff'

[colors.normal]
black = '#242424'
red = '#f62b5a'
green = '#47b413'
yellow = '#e3c401'
blue = '#24acd4'
magenta = '#f2affd'
cyan = '#13c299'
white = '#e6e6e6'

[colors.bright]
black = '#616161'
red = '#ff4d51'
green = '#35d450'
yellow = '#e9e836'
blue = '#5dc5f8'
magenta = '#feabf2'
cyan = '#24dfc4'
white = '#ffffff'

[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.2

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "Paste" }]

[selection]
save_to_clipboard = true

[env]
TERM = "alacritty"
