[window]
dimensions = { columns = 100, lines = 24 }
dynamic_padding = true
decorations = "Full"
padding = { x = 8, y = 8 }
dynamic_title = true
opacity = 0.90

[font]
normal = { family = "Hasklug Nerd Font Mono" }
size = 12

[colors]
cursor = { text = "#803333", cursor = "#803333" }
primary = { foreground = "#ffffff", background = "#170000" }

[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.2

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "Paste" }]

[selection]
save_to_clipboard = true
