
[window]
dimensions = { columns = 80, lines = 24 }
dynamic_padding = true
decorations = "Full"
padding = { x = 8, y = 8 }
dynamic_title = true

[font]
size = 12

[cursor]
style = { shape = "Underline", blinking = "On" }

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "Paste" }]

[selection]
save_to_clipboard = true
