---
name: check
on:
  push:
    branches:
      - main
    paths:
      - "setup.sh"
      - "setup_simple.sh"
      - "setup_simple_generate.sh"
      - ".bash*"
      - '.github/workflows/check.yml'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            .config
            .local
            .ssh
        env:
          SHELLCHECK_OPTS: -e SC1091 # Happy for it to not be able to follow everything
