---
name: test-deploy
on:
  push:
    branches:
      - main
    paths:
      - 'setup.sh'
      - 'setup_simple.sh'
      - 'setup_simple_generate.sh'
      - '.stow-local-ignore'
      - '.github/workflows/test-deploy.yml'

jobs:
  build:
    name: Test Deploy Dotfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run setup script simple generate
        run: bash setup_simple_generate.sh

      - name: Run setup script simple
        run: bash setup_simple.sh

      - name: Remove apt apt upgrade to save two minutes
        run: sed -i '/sudo apt-get upgrade -y/d' setup.sh && cat setup.sh

      - name: Run setup script
        run: bash setup.sh
