---
name: test-deploy
on:
  push:
    branches:
      - main
    paths:
      - "setup.sh"
      - "setup_simple.sh"
      - "setup_simple_generate.sh"
      - ".stow-local-ignore"
      - ".github/workflows/test-deploy.yml"

jobs:
  build:
    name: Test Deploy Dotfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run setup script simple generate
        run: bash setup_simple_generate.sh

      - name: Run setup script simple
        run: bash setup_simple.sh

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zsh git htop tmux curl wget tree ncdu stow software-properties-common gnupg2
          version: 1.0

      - name: Run setup script
        run: bash setup.sh --no-package-install
        timeout-minutes: 1
